'use strict';

const DEFAULT_COUNT = 1;
const MOCKS_RESTRICTIONS = {
  MIN: 1,
  MAX: 1000
};

const FILE_NAME = `mocks.json`;
const MAXIMUM_SENTENCES_ALLOWED = 5;
const DATE_SHIFT = 90;
const MAXIMUM_COMMENTS = 5;

module.exports = {
  DEFAULT_COUNT,
  MOCKS_RESTRICTIONS,
  FILE_NAME,
  MAXIMUM_SENTENCES_ALLOWED,
  DATE_SHIFT,
  MAXIMUM_COMMENTS
};
